import MonsterBuilder


def create(lb,xpos):
    xml = """
    <level>
<!-- BEGIN Monster construction -->
<sprite shape="circ" type="Enemy.EnemySprite" x="105" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar1" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="125" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar2" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="145" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar3" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="165" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar4" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="185" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar5" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="205" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar6" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="225" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar7" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="245" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar8" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="265" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar9" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="285" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar10" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="305" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar11" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="325" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar12" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="345" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar13" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="365" y="17" width="34" height="34" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_body.png" setName="caterpillar14" classname="caterpillarLimb" spritedata="caterpillar" groupIndex="-1"/>
<sprite shape="circ" type="Enemy.EnemySprite" x="75" y="20" width="40" height="40" angle="0" restitution="0.2" static="false" friction="0.5" density="5" sheet="6" firstframe="caterpillar_head.png" setName="caterpillar0" classname="caterpillarBrain" spritedata="caterpillar" groupIndex="-1"/>
<sprite type="Joints.RevoluteJoint" id="2" body1="caterpillar1" body2="caterpillar0" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="75" by="20" b2_Xoffset="0" b2_Yoffset="0" ax="105" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="3" body1="caterpillar2" body2="caterpillar1" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-9" b2_Yoffset="-8" ax="125" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="4" body1="caterpillar3" body2="caterpillar2" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-29" b2_Yoffset="-8" ax="145" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="5" body1="caterpillar4" body2="caterpillar3" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-49" b2_Yoffset="-8" ax="165" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="6" body1="caterpillar5" body2="caterpillar4" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-69" b2_Yoffset="-8" ax="185" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="7" body1="caterpillar6" body2="caterpillar5" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-89" b2_Yoffset="-8" ax="205" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="8" body1="caterpillar7" body2="caterpillar6" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-109" b2_Yoffset="-8" ax="225" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="9" body1="caterpillar8" body2="caterpillar7" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-129" b2_Yoffset="-8" ax="245" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="10" body1="caterpillar9" body2="caterpillar8" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-149" b2_Yoffset="-8" ax="265" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="11" body1="caterpillar10" body2="caterpillar9" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-169" b2_Yoffset="-8" ax="285" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="12" body1="caterpillar11" body2="caterpillar10" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-189" b2_Yoffset="-8" ax="305" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="13" body1="caterpillar12" body2="caterpillar11" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-209" b2_Yoffset="-8" ax="325" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="14" body1="caterpillar13" body2="caterpillar12" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-229" b2_Yoffset="-8" ax="345" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<sprite type="Joints.RevoluteJoint" id="15" body1="caterpillar14" body2="caterpillar13" motor_speed="2.0" torque="1000.0" enable_motor="true" lower_angle="12" upper_angle="45" enable_limit="false" collide_connected="false" bx="96" by="9" b2_Xoffset="-249" b2_Yoffset="-8" ax="365" ay="17" b1_Xoffset="0" b1_Yoffset="0"/>
<!-- END Monster construction -->
    </level>
    """
    MonsterBuilder.createFromXMLString(lb,xpos,xml)
    
